"""add tried_at and error to tech_article

Revision ID: 0c47ea6b64ec
Revises: m9o0p1q2r3s4
Create Date: 2026-04-13 08:19:13.241384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c47ea6b64ec'
down_revision: Union[str, Sequence[str], None] = 'm9o0p1q2r3s4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mtgdoku_attempt_guess_attempt_id'), table_name='mtgdoku_attempt_guess')
    op.drop_index(op.f('ix_mtgdoku_attempt_guess_oracle_id'), table_name='mtgdoku_attempt_guess')
    op.drop_index(op.f('ix_mtgdoku_guess_attempt_pos'), table_name='mtgdoku_attempt_guess')
    op.drop_table('mtgdoku_attempt_guess')
    op.drop_index(op.f('ix_mtgdoku_daily_game_day'), table_name='mtgdoku_daily_game')
    op.drop_table('mtgdoku_daily_game')
    op.drop_index(op.f('ix_mtgdoku_grid_difficulty'), table_name='mtgdoku_grid')
    op.drop_table('mtgdoku_grid')
    op.drop_index(op.f('ix_mtgdoku_attempt_day'), table_name='mtgdoku_attempt')
    op.drop_index(op.f('ix_mtgdoku_attempt_user_day'), table_name='mtgdoku_attempt')
    op.drop_index(op.f('ix_mtgdoku_attempt_user_id'), table_name='mtgdoku_attempt')
    op.drop_table('mtgdoku_attempt')
    op.drop_index(op.f('ix_familledle_attempt_user_id'), table_name='riftdle_attempt')
    op.create_index(op.f('ix_riftdle_attempt_user_id'), 'riftdle_attempt', ['user_id'], unique=False)
    op.drop_index(op.f('ix_familledle_attempt_guess_attempt_id'), table_name='riftdle_attempt_guess')
    op.drop_index(op.f('ix_familledle_attempt_guess_champion_name'), table_name='riftdle_attempt_guess')
    op.create_index(op.f('ix_riftdle_attempt_guess_attempt_id'), 'riftdle_attempt_guess', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_riftdle_attempt_guess_champion_name'), 'riftdle_attempt_guess', ['champion_name'], unique=False)
    op.drop_index(op.f('ix_familledle_daily_game_day'), table_name='riftdle_daily_game')
    op.create_index(op.f('ix_riftdle_daily_game_day'), 'riftdle_daily_game', ['day'], unique=True)
    op.drop_constraint(op.f('familledle_daily_game_champ_name_fkey'), 'riftdle_daily_game', type_='foreignkey')
    op.create_foreign_key(None, 'riftdle_daily_game', 'champ_data', ['champ_name'], ['name'])
    op.add_column('tech_article', sa.Column('tried_at', sa.DateTime(), nullable=True))
    op.add_column('tech_article', sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_tech_article_summarized'), table_name='tech_article')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tech_article_summarized'), 'tech_article', ['summarized'], unique=False)
    op.drop_column('tech_article', 'error')
    op.drop_column('tech_article', 'tried_at')
    op.drop_constraint(None, 'riftdle_daily_game', type_='foreignkey')
    op.create_foreign_key(op.f('familledle_daily_game_champ_name_fkey'), 'riftdle_daily_game', 'champ_data', ['champ_name'], ['name'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_riftdle_daily_game_day'), table_name='riftdle_daily_game')
    op.create_index(op.f('ix_familledle_daily_game_day'), 'riftdle_daily_game', ['day'], unique=True)
    op.drop_index(op.f('ix_riftdle_attempt_guess_champion_name'), table_name='riftdle_attempt_guess')
    op.drop_index(op.f('ix_riftdle_attempt_guess_attempt_id'), table_name='riftdle_attempt_guess')
    op.create_index(op.f('ix_familledle_attempt_guess_champion_name'), 'riftdle_attempt_guess', ['champion_name'], unique=False)
    op.create_index(op.f('ix_familledle_attempt_guess_attempt_id'), 'riftdle_attempt_guess', ['attempt_id'], unique=False)
    op.drop_index(op.f('ix_riftdle_attempt_user_id'), table_name='riftdle_attempt')
    op.create_index(op.f('ix_familledle_attempt_user_id'), 'riftdle_attempt', ['user_id'], unique=False)
    op.create_table('mtgdoku_attempt',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('won_easy', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('won_medium', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('won_hard', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('mtgdoku_attempt_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mtgdoku_attempt_pkey')),
    sa.UniqueConstraint('user_id', 'day', name=op.f('uq_mtgdoku_attempt_user_day'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_mtgdoku_attempt_user_id'), 'mtgdoku_attempt', ['user_id'], unique=False)
    op.create_index(op.f('ix_mtgdoku_attempt_user_day'), 'mtgdoku_attempt', ['user_id', 'day'], unique=False)
    op.create_index(op.f('ix_mtgdoku_attempt_day'), 'mtgdoku_attempt', ['day'], unique=False)
    op.create_table('mtgdoku_grid',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('difficulty_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('grid_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('content_hash', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('mtgdoku_grid_pkey')),
    sa.UniqueConstraint('content_hash', name=op.f('uq_mtgdoku_grid_content_hash'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_mtgdoku_grid_difficulty'), 'mtgdoku_grid', ['difficulty'], unique=False)
    op.create_table('mtgdoku_daily_game',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('day', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('easy_grid_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('medium_grid_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hard_grid_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['easy_grid_id'], ['mtgdoku_grid.id'], name=op.f('mtgdoku_daily_game_easy_grid_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hard_grid_id'], ['mtgdoku_grid.id'], name=op.f('mtgdoku_daily_game_hard_grid_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['medium_grid_id'], ['mtgdoku_grid.id'], name=op.f('mtgdoku_daily_game_medium_grid_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('mtgdoku_daily_game_pkey')),
    sa.UniqueConstraint('day', name=op.f('uq_mtgdoku_daily_game_day'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_mtgdoku_daily_game_day'), 'mtgdoku_daily_game', ['day'], unique=True)
    op.create_table('mtgdoku_attempt_guess',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('cell_row', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('cell_col', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('oracle_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('is_valid', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['mtgdoku_attempt.id'], name=op.f('mtgdoku_attempt_guess_attempt_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['oracle_id'], ['mtg_card.oracle_id'], name=op.f('mtgdoku_attempt_guess_oracle_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('mtgdoku_attempt_guess_pkey'))
    )
    op.create_index(op.f('ix_mtgdoku_guess_attempt_pos'), 'mtgdoku_attempt_guess', ['attempt_id', 'position'], unique=False)
    op.create_index(op.f('ix_mtgdoku_attempt_guess_oracle_id'), 'mtgdoku_attempt_guess', ['oracle_id'], unique=False)
    op.create_index(op.f('ix_mtgdoku_attempt_guess_attempt_id'), 'mtgdoku_attempt_guess', ['attempt_id'], unique=False)
    # ### end Alembic commands ###
