"""add FamilledleAttempt

Revision ID: 53e02020ecdd
Revises: f789d25a7a46
Create Date: 2026-02-15 17:16:12.476167

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "53e02020ecdd"
down_revision: Union[str, Sequence[str], None] = "f789d25a7a46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "familledle_attempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("try_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "day", name="uq_familledle_attempt_user_day"),
    )
    op.create_index(
        "ix_familledle_attempt_day", "familledle_attempt", ["day"], unique=False
    )
    op.create_index(
        "ix_familledle_attempt_user_day",
        "familledle_attempt",
        ["user_id", "day"],
        unique=False,
    )
    op.create_index(
        op.f("ix_familledle_attempt_user_id"),
        "familledle_attempt",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "familledle_attempt_guess",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attempt_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("champion_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["familledle_attempt.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["champion_name"], ["champ_data.name"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("attempt_id", "position", name="uq_attempt_guess_position"),
    )
    op.create_index(
        "ix_attempt_guess_attempt_pos",
        "familledle_attempt_guess",
        ["attempt_id", "position"],
        unique=False,
    )
    op.create_index(
        op.f("ix_familledle_attempt_guess_attempt_id"),
        "familledle_attempt_guess",
        ["attempt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_familledle_attempt_guess_champion_name"),
        "familledle_attempt_guess",
        ["champion_name"],
        unique=False,
    )
    op.drop_constraint(op.f("fk_user_pending_email"), "user", type_="foreignkey")
    op.drop_constraint(op.f("fk_user_primary_email"), "user", type_="foreignkey")
    op.create_foreign_key(
        "fk_user_primary_email",
        "user",
        "user_email_address",
        ["primary_email_id"],
        ["id"],
        use_alter=True,
    )
    op.create_foreign_key(
        "fk_user_pending_email",
        "user",
        "user_email_address",
        ["pending_email_id"],
        ["id"],
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_pending_email", "user", type_="foreignkey")
    op.drop_constraint("fk_user_primary_email", "user", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_user_primary_email"),
        "user",
        "user_email_address",
        ["primary_email_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_user_pending_email"),
        "user",
        "user_email_address",
        ["pending_email_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(
        op.f("ix_familledle_attempt_guess_champion_name"),
        table_name="familledle_attempt_guess",
    )
    op.drop_index(
        op.f("ix_familledle_attempt_guess_attempt_id"),
        table_name="familledle_attempt_guess",
    )
    op.drop_index("ix_attempt_guess_attempt_pos", table_name="familledle_attempt_guess")
    op.drop_table("familledle_attempt_guess")
    op.drop_index(
        op.f("ix_familledle_attempt_user_id"), table_name="familledle_attempt"
    )
    op.drop_index("ix_familledle_attempt_user_day", table_name="familledle_attempt")
    op.drop_index("ix_familledle_attempt_day", table_name="familledle_attempt")
    op.drop_table("familledle_attempt")
    # ### end Alembic commands ###
