"""ajout is_active on mail

Revision ID: 90ee9a71da75
Revises: b3f92772b9f3
Create Date: 2025-12-23 14:54:03.719833

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90ee9a71da75"
down_revision: Union[str, Sequence[str], None] = "b3f92772b9f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_email_address", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_email_address", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    # ### end Alembic commands ###
