"""list verifToken dans mail

Revision ID: 9e265b3c3aa8
Revises: 90ee9a71da75
Create Date: 2025-12-23 18:10:18.755131

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "9e265b3c3aa8"
down_revision: Union[str, Sequence[str], None] = "90ee9a71da75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_verification_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["user_email_address.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("email_verification_token", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_email_verification_token_consumed_at"),
            ["consumed_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_email_verification_token_email_id"),
            ["email_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_email_verification_token_expires_at"),
            ["expires_at"],
            unique=False,
        )

    with op.batch_alter_table("emailverificationtoken", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_emailverificationtoken_consumed_at"))
        batch_op.drop_index(batch_op.f("ix_emailverificationtoken_email_id"))
        batch_op.drop_index(batch_op.f("ix_emailverificationtoken_expires_at"))

    op.drop_table("emailverificationtoken")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emailverificationtoken",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("email_id", sa.INTEGER(), nullable=False),
        sa.Column("token_hash", sa.VARCHAR(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("expires_at", sa.DATETIME(), nullable=False),
        sa.Column("consumed_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["user_email_address.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("emailverificationtoken", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_emailverificationtoken_expires_at"),
            ["expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_emailverificationtoken_email_id"), ["email_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_emailverificationtoken_consumed_at"),
            ["consumed_at"],
            unique=False,
        )

    with op.batch_alter_table("email_verification_token", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_verification_token_expires_at"))
        batch_op.drop_index(batch_op.f("ix_email_verification_token_email_id"))
        batch_op.drop_index(batch_op.f("ix_email_verification_token_consumed_at"))

    op.drop_table("email_verification_token")
    # ### end Alembic commands ###
