"""ajout MtgBulkSyncState

Revision ID: a82d04ff7dfa
Revises: 784253d57612
Create Date: 2026-03-18 15:25:36.147486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a82d04ff7dfa'
down_revision: Union[str, Sequence[str], None] = '784253d57612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mtg_bulk_sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulk_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('remote_bulk_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('remote_updated_at', sa.DateTime(), nullable=True),
    sa.Column('remote_download_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('remote_size', sa.Integer(), nullable=True),
    sa.Column('last_downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('last_downloaded_file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_imported_bulk_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_imported_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mtg_bulk_sync_state')
    # ### end Alembic commands ###
