"""ajout mtg_card

Revision ID: ac8a44d34c70
Revises: ff325c6b49d3
Create Date: 2026-03-17 17:49:10.304334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac8a44d34c70'
down_revision: Union[str, Sequence[str], None] = 'ff325c6b49d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mtg_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oracle_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('image_url_small', sa.Text(), nullable=True),
    sa.Column('image_url_medium', sa.Text(), nullable=True),
    sa.Column('color_identity', postgresql.ARRAY(sa.String(length=1)), nullable=False),
    sa.Column('converted_mana_cost', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oracle_id', name='uq_mtg_card_oracle_id')
    )
    op.create_index('ix_mtg_card_name', 'mtg_card', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mtg_card_name', table_name='mtg_card')
    op.drop_table('mtg_card')
    # ### end Alembic commands ###
