"""CHanged FK to columns and use_alter

Revision ID: b3f92772b9f3
Revises: bacb5dcdfa4f
Create Date: 2025-12-21 02:32:23.613057

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b3f92772b9f3"
down_revision: Union[str, Sequence[str], None] = "bacb5dcdfa4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_pending_email_id"))
        batch_op.drop_index(batch_op.f("ix_user_primary_email_id"))

    with op.batch_alter_table("user_email_address", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.drop_index(batch_op.f("ix_user_email_address_user_id"))
        batch_op.drop_index(
            batch_op.f("uq_verified_email"),
            sqlite_where=sa.text("verified_at IS NOT NULL"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_email_address", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("uq_verified_email"),
            ["email"],
            unique=1,
            sqlite_where=sa.text("verified_at IS NOT NULL"),
        )
        batch_op.create_index(
            batch_op.f("ix_user_email_address_user_id"), ["user_id"], unique=False
        )
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_primary_email_id"), ["primary_email_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_pending_email_id"), ["pending_email_id"], unique=False
        )

    # ### end Alembic commands ###
