"""init

Revision ID: bacb5dcdfa4f
Revises:
Create Date: 2025-12-21 01:24:24.357034

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "bacb5dcdfa4f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("primary_email_id", sa.Integer(), nullable=True),
        sa.Column("pending_email_id", sa.Integer(), nullable=True),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_pending_email_id"), ["pending_email_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_primary_email_id"), ["primary_email_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table(
        "user_email_address",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column("verification_sent_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_email_address", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_email_address_email"), ["email"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_email_address_user_id"), ["user_id"], unique=False
        )
    
    op.create_foreign_key(
    "fk_user_pending_email",
    "user",
    "user_email_address",
    ["pending_email_id"],
    ["id"],
    ondelete="SET NULL",
    )

    op.create_foreign_key(
        "fk_user_primary_email",
        "user",
        "user_email_address",
        ["primary_email_id"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_table(
        "emailverificationtoken",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["email_id"],
            ["user_email_address.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("emailverificationtoken", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_emailverificationtoken_consumed_at"),
            ["consumed_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_emailverificationtoken_email_id"), ["email_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_emailverificationtoken_expires_at"),
            ["expires_at"],
            unique=False,
        )

    op.create_table(
        "passwordresettoken",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("passwordresettoken", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_passwordresettoken_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_passwordresettoken_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_passwordresettoken_used_at"), ["used_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_passwordresettoken_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "usersession",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "session_token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("idle_expires_at", sa.DateTime(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # Unicity on verified email
    op.execute(
        """
        CREATE UNIQUE INDEX uq_verified_email
        ON user_email_address(email)
        WHERE verified_at IS NOT NULL;
    """
    )
    with op.batch_alter_table("usersession", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_usersession_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_usersession_idle_expires_at"),
            ["idle_expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_usersession_revoked_at"), ["revoked_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_usersession_session_token_hash"),
            ["session_token_hash"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_usersession_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("fk_user_primary_email", "user", type_="foreignkey")
    op.drop_constraint("fk_user_pending_email", "user", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usersession", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usersession_user_id"))
        batch_op.drop_index(batch_op.f("ix_usersession_session_token_hash"))
        batch_op.drop_index(batch_op.f("ix_usersession_revoked_at"))
        batch_op.drop_index(batch_op.f("ix_usersession_idle_expires_at"))
        batch_op.drop_index(batch_op.f("ix_usersession_expires_at"))

    op.drop_table("usersession")
    with op.batch_alter_table("passwordresettoken", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_passwordresettoken_user_id"))
        batch_op.drop_index(batch_op.f("ix_passwordresettoken_used_at"))
        batch_op.drop_index(batch_op.f("ix_passwordresettoken_token_hash"))
        batch_op.drop_index(batch_op.f("ix_passwordresettoken_expires_at"))

    op.drop_table("passwordresettoken")
    with op.batch_alter_table("emailverificationtoken", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_emailverificationtoken_expires_at"))
        batch_op.drop_index(batch_op.f("ix_emailverificationtoken_email_id"))
        batch_op.drop_index(batch_op.f("ix_emailverificationtoken_consumed_at"))

    op.drop_table("emailverificationtoken")
    with op.batch_alter_table("user_email_address", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_email_address_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_email_address_email"))

    op.drop_table("user_email_address")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))
        batch_op.drop_index(batch_op.f("ix_user_primary_email_id"))
        batch_op.drop_index(batch_op.f("ix_user_pending_email_id"))

    op.execute("DROP INDEX IF EXISTS uq_verified_email;")

    op.drop_table("user")
    # ### end Alembic commands ###
