"""ajout mtg_tag

Revision ID: f91b9e210e89
Revises: a82d04ff7dfa
Create Date: 2026-03-18 18:26:23.183227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f91b9e210e89'
down_revision: Union[str, Sequence[str], None] = 'a82d04ff7dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_deck_user_id_name')
    )
    op.create_index(op.f('ix_deck_name'), 'deck', ['name'], unique=False)
    op.create_index(op.f('ix_deck_user_id'), 'deck', ['user_id'], unique=False)
    op.create_table('deck_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('mtg_card_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('zone', sa.Enum('MAINBOARD', 'SIDEBOARD', 'COMMANDER', 'MAYBEBOARD', name='deckentryzone'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.ForeignKeyConstraint(['mtg_card_id'], ['mtg_card.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_id', 'mtg_card_id', 'zone', name='uq_deck_entry_deck_card_zone')
    )
    op.create_index(op.f('ix_deck_entry_deck_id'), 'deck_entry', ['deck_id'], unique=False)
    op.create_index(op.f('ix_deck_entry_mtg_card_id'), 'deck_entry', ['mtg_card_id'], unique=False)
    op.create_table('tag_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('tag_kind', sa.Enum('STRATEGY', 'CARD_TYPE', 'MANA_VALUE', 'USER_ONLY', 'COLOR_IDENTITY', name='tagkind'), nullable=False),
    sa.Column('value_kind', sa.Enum('NONE', 'OPTION', 'INTEGER', name='tagvaluekind'), nullable=False),
    sa.Column('has_rate', sa.Boolean(), nullable=False),
    sa.Column('minimum_per_entry', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_definition_deck_id'), 'tag_definition', ['deck_id'], unique=False)
    op.create_index(op.f('ix_tag_definition_name'), 'tag_definition', ['name'], unique=False)
    op.create_index(op.f('ix_tag_definition_tag_kind'), 'tag_definition', ['tag_kind'], unique=False)
    op.create_table('tag_value_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_definition_id', sa.Integer(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('normalized_value', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tag_definition_id'], ['tag_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_definition_id', 'normalized_value', name='uq_tag_value_option_definition_normalized_value')
    )
    op.create_index(op.f('ix_tag_value_option_normalized_value'), 'tag_value_option', ['normalized_value'], unique=False)
    op.create_index(op.f('ix_tag_value_option_tag_definition_id'), 'tag_value_option', ['tag_definition_id'], unique=False)
    op.create_table('deck_entry_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_entry_id', sa.Integer(), nullable=False),
    sa.Column('tag_definition_id', sa.Integer(), nullable=False),
    sa.Column('tag_value_option_id', sa.Integer(), nullable=True),
    sa.Column('integer_value', sa.Integer(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('source_kind', sa.Enum('DERIVED', 'USER', name='tagsourcekind'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deck_entry_id'], ['deck_entry.id'], ),
    sa.ForeignKeyConstraint(['tag_definition_id'], ['tag_definition.id'], ),
    sa.ForeignKeyConstraint(['tag_value_option_id'], ['tag_value_option.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deck_entry_tag_deck_entry_id'), 'deck_entry_tag', ['deck_entry_id'], unique=False)
    op.create_index(op.f('ix_deck_entry_tag_tag_definition_id'), 'deck_entry_tag', ['tag_definition_id'], unique=False)
    op.create_index(op.f('ix_deck_entry_tag_tag_value_option_id'), 'deck_entry_tag', ['tag_value_option_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deck_entry_tag_tag_value_option_id'), table_name='deck_entry_tag')
    op.drop_index(op.f('ix_deck_entry_tag_tag_definition_id'), table_name='deck_entry_tag')
    op.drop_index(op.f('ix_deck_entry_tag_deck_entry_id'), table_name='deck_entry_tag')
    op.drop_table('deck_entry_tag')
    op.drop_index(op.f('ix_tag_value_option_tag_definition_id'), table_name='tag_value_option')
    op.drop_index(op.f('ix_tag_value_option_normalized_value'), table_name='tag_value_option')
    op.drop_table('tag_value_option')
    op.drop_index(op.f('ix_tag_definition_tag_kind'), table_name='tag_definition')
    op.drop_index(op.f('ix_tag_definition_name'), table_name='tag_definition')
    op.drop_index(op.f('ix_tag_definition_deck_id'), table_name='tag_definition')
    op.drop_table('tag_definition')
    op.drop_index(op.f('ix_deck_entry_mtg_card_id'), table_name='deck_entry')
    op.drop_index(op.f('ix_deck_entry_deck_id'), table_name='deck_entry')
    op.drop_table('deck_entry')
    op.drop_index(op.f('ix_deck_user_id'), table_name='deck')
    op.drop_index(op.f('ix_deck_name'), table_name='deck')
    op.drop_table('deck')
    # ### end Alembic commands ###
